#' Generate tree file
#'
#' @param treefile Aphylogenetic tree file (Only tested for tree generated by iqtree)
#' @param tree_type Currently 4 types of tree supported, `normal`, `newick`,
#' `raxml`, `iqtree` (default).
#' @param tree_attrib A data frame with first columns match node names of tree file.
#' @param tree_msa A multiple-aligned fasta file used to generate the tree file.
#' A tree with Multiple-Sequence-Alignment plot would be generated when given.
#' @param color_branches Name of columns in `tree_attrib` used for color branches.
#' @inheritParams ggtree::ggtree
#' @param tip_text Show branch labels or supply a name of columns in `tree_attrib` to be
#' shown as branch labels, Or `label` to show default labels, or NULL to not show
#' branch labels.
#' @param tip_text_size Text size of branch labels.
#' @param bootstrap Show bootstrap value or not.
#' @param bootstrap_variable `node` to label ids for each node, or other variables in
#' `tree` object. Default `UFboot` would
#' be used for `tree_type=iqtree`.
#' @param bootstrap_size Text size of bootstrap labels.
#' @inheritParams sp_manual_color_ggplot2
#' @param bootstrap_color Text color of bootstrap labels.
#' @inheritParams sp_ggplot_layout
#'
#' @return A ggplot2 object
#' @export
#'
#' @examples
#'
#' library(ggtree)
#' library("ggplot2")
#' library(ImageGP)
#' treefile <- "iqtree.treefile"
#' sp_tree_plot(treefile)
sp_tree_plot <-
  function(treefile,
           tree_type = 'iqtree',
           tree_attrib = NULL,
           tree_msa = NULL,
           color_branches = NULL,
           layout = "fan",
           ladderize = F,
           branch.length = "none",
           tip_text = 'label',
           tip_text_size = 3,
           bootstrap = TRUE,
           bootstrap_variable = NULL,
           legend.position = "bottom",
           bootstrap_size = 3,
           bootstrap_color = 'red',
           debug = FALSE,
		   manual_color_vector = 'Set3', 
           ...) {
    if (debug) {
      # tree_type = 'iqtree'
      # tree_attrib = NULL
      # tree_msa = NULL
      # color_branches = NULL
      # layout = "fan"
      # ladderize = F
      # branch.length = "none"
      # tip_text = 'label'
      # tip_text_size = 3
      # bootstrap = TRUE
      # bootstrap_variable = NULL
      # legend.position = "bottom"
      # bootstrap_size = 3
      # bootstrap_color = 'red'
      argg <- c(as.list(environment()), list(...))
      print(argg)
    }
    sp_read_tree <- function(treefile, type1) {
      switch(
        type1,
        iqtree = read.iqtree(treefile),
        newick = read.newick(treefile),
        raxml = read.raxml(treefile),
        normal = read.tree(treefile)
      )
    }

    if (sp.is.null(tree_type)) {
      tree <- read.tree(treefile)
    } else{
      tree <- sp_read_tree(treefile, tree_type)
    }
    if (!sp.is.null(tree_attrib)) {
      tree_attrib_df <- sp_readTable(tree_attrib, row.names = 1)

      tree_attrib_df <-
        data.frame(node = nodeid(tree, rownames(tree_attrib_df)),
                   tree_attrib_df)

      tree <- dplyr::full_join(tree, tree_attrib_df, by = "node")
    }

    p <-
      ggtree(
        tree,
        layout = layout,
        ladderize = ladderize,
        branch.length = branch.length,
        ...
      )

    attribute_var = colnames(p$data)

    if (!is.null(tip_text)) {
      if (tip_text == "label") {
        p <- p +
          geom_tiplab(aes(angle = angle),
                      size = tip_text_size,
                      show.legend = F)
      } else{
        tip_text = sym(tip_text)
        p <- p +
          geom_tiplab(aes(angle = angle, label = !!tip_text),
                      size = tip_text_size,
                      show.legend = F)
      }

    }

    if (is.character(bootstrap)) {
      bootstrap = as.logical(bootstrap)
    }

    if (bootstrap) {
      if (sp.is.null(bootstrap_variable)) {
        bootstrap_variable = switch(tree_type,
                                    iqtree = "UFboot")
      }

	  print(paste0("Get default bootstrap value for tree: ", bootstrap_variable))

      if (bootstrap_variable %in% attribute_var) {
		print(paste0("Use default bootstrap value for tree: ", bootstrap_variable))
        bootstrap_variable = sym(bootstrap_variable)

        p <- p + geom_nodelab(
          aes(
            subset = !isTip,
            label = !!bootstrap_variable
          ),
          hjust = -.3,
          color = bootstrap_color,
          size = bootstrap_size
        )
      } else {
        stop(paste0(bootstrap_variable, "is not a valid attribute."))
      }

    }


    if (!sp.is.null(color_branches)) {
      if (color_branches %in% attribute_var) {
        color_branches_en = sym(color_branches)
        p <- p + aes(color = !!color_branches_en)
		p <- sp_manual_color_ggplot2(p, tree, color_branches, manual_color_vector)
      } else {
        stop(paste0(color_branches, "is not a valid attribute."))
      }
    }

    p <- p + theme(legend.position = legend.position)

    p <- p + geom_treescale()

    if (!sp.is.null(tree_msa)) {
      p <- msaplot(p, tree_msa, offset = 2, width = 2)
    }

    p
  }
